name: Node.js CI/CD 

on:
  push:
    branches:
      - main

jobs:
  teste-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Inicia container
        run: docker-compose up -d

  SAST-snyk-dependencies:
    needs: teste-unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install and configure SNYK
        run: |
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Run SAST scan for lib vulnerabilities
        run: snyk test .

  SAST-njsscan-patterns:
    needs: teste-unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests_html njsscan
      - name: Run NJSScan
        run: njsscan .

  DAST-SOOS:
    needs: teste-unit
    name: SOOS DAST Baseline Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@v1.2.5
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "DevSecOps"
          scan_mode: "baseline"
          target_url: "https://dwtwut-3000.csb.app/"

  deploy-:
    needs: [teste-unit, SAST-njsscan-patterns, DAST-SOOS, SAST-snyk-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: c4st4nha/projetosrc
          tag: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
